
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action ApplicationAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.VBox mainVBox;
	private global::Gtk.MenuBar mainMenu;
	private global::Gtk.ScrolledWindow scrolledWindow;
	private global::Gtk.Statusbar statusBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ApplicationAction = new global::Gtk.Action ("ApplicationAction", global::Mono.Unix.Catalog.GetString ("Application"), null, null);
		this.ApplicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Application");
		w1.Add (this.ApplicationAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVBox = new global::Gtk.VBox ();
		this.mainVBox.Name = "mainVBox";
		this.mainVBox.Spacing = 6;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainMenu'><menu name='ApplicationAction' action='ApplicationAction'><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.mainMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainMenu")));
		this.mainMenu.Name = "mainMenu";
		this.mainVBox.Add (this.mainMenu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.mainMenu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.scrolledWindow = new global::Gtk.ScrolledWindow ();
		this.scrolledWindow.CanFocus = true;
		this.scrolledWindow.Name = "scrolledWindow";
		this.scrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.mainVBox.Add (this.scrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.scrolledWindow]));
		w3.Position = 1;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.statusBar = new global::Gtk.Statusbar ();
		this.statusBar.Name = "statusBar";
		this.statusBar.Spacing = 6;
		this.mainVBox.Add (this.statusBar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.statusBar]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.mainVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
	}
}
