language: csharp
mono:
    - weekly
sudo: false
solution: KAOSTools.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe
install:
  - mono .nuget/nuget.exe restore KAOSTools.sln
  - mono .nuget/nuget.exe install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug KAOSTools.sln
  - mono testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe
      ./bin/Parsing.Tests/Debug/KAOSTools.Parsing.Tests.dll
      ./bin/Debug/UCLouvain.KAOSTools.Propagators.Tests.dll
