// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Beaver.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Formal specifications for goal models")]
    public partial class FormalSpecificationsForGoalModelsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        #line 1 "formal.feature"
        #line hidden
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Formal specifications for goal models", "As a modeler\nI want to specify my goal formally\nSo that I can perform automated checks", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line 7
    testRunner.Given("a model");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Formal specification of goals")]
        public virtual void FormalSpecificationOfGoals()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Formal specification of goals", ((string[])(null)));
#line 9
  this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 10
    testRunner.Given("a goal 'goal-1'");
#line 11
    testRunner.When("I specify 'goal-1' as 'G (current -> F target)'");
#line 12
    testRunner.Then("the goal 'goal-1' is formally specified");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Formal specification of domain properties")]
        public virtual void FormalSpecificationOfDomainProperties()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Formal specification of domain properties", ((string[])(null)));
#line 14
  this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 15
    testRunner.Given("a domain property 'domprop-1'");
#line 16
    testRunner.When("I specify 'domprop-1' as 'G (current -> G goodCondition)'");
#line 17
    testRunner.Then("the domain property 'domprop-1' is formally specified");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Formal specification of obstacles")]
        public virtual void FormalSpecificationOfObstacles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Formal specification of obstacles", ((string[])(null)));
#line 19
  this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 20
    testRunner.Given("an obstacle 'obstacle-1'");
#line 21
    testRunner.When("I specify 'obstacle-1' as 'F (current & G !target)'");
#line 22
    testRunner.Then("the obstacle 'obstacle-1' is formally specified");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
